/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pctFormulario;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import pctControle.Anime;
import pctControle.Usuario;
import pctDAO.AnimeDAO;
import pctDAO.ReviewDAO;
import pctControle.Review;

/**
 *
 * @author Luis Henrique
 */
public class ConsultaReview extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaReview
     */
    private Usuario user;
    private String comp = "";
    List<Anime> AnimeList = null;
    private List<Review> reviews = null;
    
    protected boolean a = false;
    
    public ConsultaReview(Usuario user) {
        if (user != null){
            initComponents();
            this.user = user;
            ListarAnimes();
            userLabel.setText("Usuário: "+user.getUsername());
            FilterJComboBox();
            GetReviews();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultTable = new javax.swing.JTable();
        digiteAnimeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bigtxtReview = new javax.swing.JTextPane();
        reviewLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCreateReview = new javax.swing.JButton();
        boxAnimes = new javax.swing.JComboBox<>();
        userLabel = new javax.swing.JLabel();
        btnUpdateReview = new javax.swing.JButton();
        btnexcluirReview = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        consultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuário", "Nota", "Review", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        consultTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        consultTable.getTableHeader().setReorderingAllowed(false);
        consultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultTableMouseClicked(evt);
            }
        });
        consultTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(consultTable);
        if (consultTable.getColumnModel().getColumnCount() > 0) {
            consultTable.getColumnModel().getColumn(0).setResizable(false);
            consultTable.getColumnModel().getColumn(0).setPreferredWidth(75);
            consultTable.getColumnModel().getColumn(1).setResizable(false);
            consultTable.getColumnModel().getColumn(1).setPreferredWidth(5);
            consultTable.getColumnModel().getColumn(2).setResizable(false);
            consultTable.getColumnModel().getColumn(2).setPreferredWidth(400);
            consultTable.getColumnModel().getColumn(3).setResizable(false);
            consultTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        digiteAnimeLabel.setText("Digite o nome do Anime:");

        bigtxtReview.setEditable(false);
        jScrollPane2.setViewportView(bigtxtReview);

        reviewLabel.setText("Review:");

        btnBack.setText("Home");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateReview.setText("Criar Review");
        btnCreateReview.setEnabled(false);
        btnCreateReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateReviewActionPerformed(evt);
            }
        });

        boxAnimes.setEditable(true);
        boxAnimes.setToolTipText("Selecione um Anime");
        boxAnimes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxAnimesItemStateChanged(evt);
            }
        });

        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Usuário: ");

        btnUpdateReview.setText("Editar");
        btnUpdateReview.setEnabled(false);
        btnUpdateReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateReviewActionPerformed(evt);
            }
        });

        btnexcluirReview.setText("Excluir");
        btnexcluirReview.setEnabled(false);
        btnexcluirReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(digiteAnimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(565, 565, 565))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreateReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(67, 67, 67)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnUpdateReview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexcluirReview))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reviewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(666, 666, 666))
                    .addComponent(boxAnimes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(digiteAnimeLabel)
                .addGap(4, 4, 4)
                .addComponent(boxAnimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnCreateReview)
                    .addComponent(userLabel)
                    .addComponent(btnUpdateReview)
                    .addComponent(btnexcluirReview))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateReviewActionPerformed
        new pctFormulario.Review(this.user, (Anime) boxAnimes.getSelectedItem(), this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateReviewActionPerformed

    private void boxAnimesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxAnimesItemStateChanged
        if (boxAnimes.getSelectedIndex() != -1 && this.a){
            btnCreateReview.setEnabled(true);
            consultTable.clearSelection();
            btnUpdateReview.setEnabled(false);
            btnexcluirReview.setEnabled(false);
            bigtxtReview.setText("");
            ListarReviews((Anime) boxAnimes.getSelectedItem());
        }else{
            DefaultTableModel dados = (DefaultTableModel) consultTable.getModel();
            dados.setNumRows(0);
        }
    }//GEN-LAST:event_boxAnimesItemStateChanged

    private void consultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultTableMouseClicked
        Review r = (Review) consultTable.getValueAt(consultTable.getSelectedRow(), 2);
        bigtxtReview.setText(r.getDescricao());
        if (r.getId_user() == this.user.getIduser()){
            btnUpdateReview.setEnabled(true);
            btnexcluirReview.setEnabled(true);
        }else{
            btnUpdateReview.setEnabled(false);
            btnexcluirReview.setEnabled(false);
        }
    }//GEN-LAST:event_consultTableMouseClicked

    private void consultTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultTableKeyReleased
        if (evt.getKeyCode()== 40 || evt.getKeyCode() == 38){
            Review r = (Review) consultTable.getValueAt(consultTable.getSelectedRow(), 2);
            bigtxtReview.setText(r.getDescricao());
            if (r.getId_user() == this.user.getIduser()){
                btnUpdateReview.setEnabled(true);
                btnexcluirReview.setEnabled(true);
            }else{
                btnUpdateReview.setEnabled(false);
                btnexcluirReview.setEnabled(false);
            }
        }
    }//GEN-LAST:event_consultTableKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new HomeUsuario(this.user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateReviewActionPerformed
        new pctFormulario.Review(this.user, (Anime) boxAnimes.getSelectedItem(), this, (Review) consultTable.getValueAt(consultTable.getSelectedRow(), 2)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdateReviewActionPerformed

    private void btnexcluirReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirReviewActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Deseja Excluir?");
        if (a == 0){
            pctControle.Review review = (Review) consultTable.getValueAt(consultTable.getSelectedRow(), 2);
            ReviewDAO dao = new ReviewDAO();
           
            dao.excluirReview(review);
            GetReviews();
            ListarReviews((Anime) boxAnimes.getSelectedItem());
        }        
    }//GEN-LAST:event_btnexcluirReviewActionPerformed

    private void ListarAnimes(){
        DefaultComboBoxModel dados = (DefaultComboBoxModel) boxAnimes.getModel();
        dados.removeAllElements();
        
        AnimeDAO dao = new AnimeDAO();
        this.AnimeList = dao.listarAnimes();
        boolean c = true;
        for (Anime anime : this.AnimeList){
            if (c){
                c = false;
                this.a = false;
            }else{
                boxAnimes.setSelectedIndex(-1);
                this.a = true;
            }
            dados.addElement(anime);
        }
        
        btnCreateReview.setEnabled(false);
    }
    private void GetReviews(){
        ReviewDAO dao = new ReviewDAO();
        this.reviews = dao.listarAllReviews(this.user.getIduser());
    }
    private void ListarReviews(Anime anime){
        DefaultTableModel dados = (DefaultTableModel) consultTable.getModel();
        dados.setNumRows(0);
        //ReviewDAO dao = new ReviewDAO();
        //List<Review> lista = dao.listarReviews(anime);
        //for (Review review : lista){
        for (Review review : this.reviews){
            if (review.getId_Anime() == anime.getIdanime()){
                dados.addRow(new Object[]{
                    review.getUser(),
                    review.getNota(),
                    review,
                    review.getDataString()
                });
                if (review.getId_user() == this.user.getIduser()){
                    btnCreateReview.setEnabled(false);
                }
            }
        }
    }
    private void FilterJComboBox(){
        AutoCompleteDecorator.decorate(boxAnimes);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JOptionPane.showMessageDialog(null, "Faça Login!");
        new Login().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane bigtxtReview;
    private javax.swing.JComboBox<String> boxAnimes;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateReview;
    private javax.swing.JButton btnUpdateReview;
    private javax.swing.JButton btnexcluirReview;
    private javax.swing.JTable consultTable;
    private javax.swing.JLabel digiteAnimeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel reviewLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
