/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pctFormulario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pctControle.Anime;
import pctControle.Estudio;
import pctControle.Genero;
import pctDAO.AnimeDAO;
import pctDAO.EstudioDAO;
import pctDAO.GeneroDAO;

/**
 *
 * @author Luis Henrique
 */
public class GerenciaAnime extends javax.swing.JFrame {

    /**
     * Creates new form GerenciaAnime
     */
    
    public GerenciaAnime() {
        initComponents();
        ListarAnimes();
        BuscarEstudios();
        BuscarGeneros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        consultAnimeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultAnimeTable = new javax.swing.JTable();
        txtConsultAnime = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        bigtxtConsultAnimeSin = new javax.swing.JTextPane();
        ConsultAnimeSinLabel = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nameAnimeLabel = new javax.swing.JLabel();
        txtNameAnime = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        boxGender = new javax.swing.JComboBox<>();
        boxEstudio = new javax.swing.JComboBox<>();
        estudioLabel = new javax.swing.JLabel();
        faixaLabel = new javax.swing.JLabel();
        boxFaixa = new javax.swing.JComboBox<>();
        sinopseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bigtxtSinopse = new javax.swing.JTextPane();
        btnClearAnime = new javax.swing.JButton();
        btnCadastraAnime = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listGeneros = new javax.swing.JList<>();
        listGeneros.setModel(new DefaultListModel<>());
        btnAdicionarGenero = new javax.swing.JButton();

        jLabel2.setText("Estudio");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton4.setText("Cadatrar Estudio");

        jLabel1.setText("Digite o nome do Estudio:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultAnimeLabel.setText("Digite o nome do Anime:");

        ConsultAnimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdAnime", "Nome", "Faixa Etária", "Media", "Gênero", "Estudio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ConsultAnimeTable.getTableHeader().setReorderingAllowed(false);
        ConsultAnimeTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConsultAnimeTableFocusGained(evt);
            }
        });
        ConsultAnimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultAnimeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ConsultAnimeTable);
        if (ConsultAnimeTable.getColumnModel().getColumnCount() > 0) {
            ConsultAnimeTable.getColumnModel().getColumn(0).setResizable(false);
            ConsultAnimeTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            ConsultAnimeTable.getColumnModel().getColumn(1).setResizable(false);
            ConsultAnimeTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            ConsultAnimeTable.getColumnModel().getColumn(2).setResizable(false);
            ConsultAnimeTable.getColumnModel().getColumn(2).setPreferredWidth(10);
            ConsultAnimeTable.getColumnModel().getColumn(3).setResizable(false);
            ConsultAnimeTable.getColumnModel().getColumn(3).setPreferredWidth(20);
            ConsultAnimeTable.getColumnModel().getColumn(4).setResizable(false);
            ConsultAnimeTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            ConsultAnimeTable.getColumnModel().getColumn(5).setResizable(false);
            ConsultAnimeTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        bigtxtConsultAnimeSin.setEditable(false);
        jScrollPane3.setViewportView(bigtxtConsultAnimeSin);

        ConsultAnimeSinLabel.setText("Sinopse:");

        btnUpdate.setText("Atualizar");

        btnUpdate1.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(consultAnimeLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConsultAnimeSinLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnUpdate)
                                            .addComponent(btnUpdate1))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultAnime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(consultAnimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultAnime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultAnimeSinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Animes", jPanel1);

        nameAnimeLabel.setText("Nome:");

        txtNameAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameAnimeActionPerformed(evt);
            }
        });

        genderLabel.setText("Gênero:");

        estudioLabel.setText("Estudio:");

        faixaLabel.setText("Faixa Etária:");

        boxFaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "+18", "+16", "+14", "+12", "+10", "L" }));

        sinopseLabel.setText("Sinopse:");

        jScrollPane1.setViewportView(bigtxtSinopse);

        btnClearAnime.setText("Limpar");

        btnCadastraAnime.setText("Cadatrar");
        btnCadastraAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraAnimeActionPerformed(evt);
            }
        });

        listGeneros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(listGeneros);

        btnAdicionarGenero.setText("Adicionar");
        btnAdicionarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estudioLabel)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameAnimeLabel)
                            .addComponent(txtNameAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(boxEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(faixaLabel)
                            .addComponent(boxFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnCadastraAnime)
                                .addGap(79, 79, 79)
                                .addComponent(btnClearAnime)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinopseLabel))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameAnimeLabel)
                    .addComponent(sinopseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNameAnime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(estudioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(boxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdicionarGenero))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(boxEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(faixaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCadastraAnime)
                                    .addComponent(btnClearAnime)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Animes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtNameAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameAnimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameAnimeActionPerformed

    private void btnAdicionarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarGeneroActionPerformed
        DefaultListModel lista = (DefaultListModel) listGeneros.getModel();
        int tam = lista.getSize();
        boolean v = false;
        Genero select = (Genero) boxGender.getSelectedItem();
        for (int i = 0; i < tam; i++){
            Genero temp = (Genero) lista.get(i);
            if (temp.equals(select)){
                v = true;
                break;
            }
        }
        if (v){
            JOptionPane.showMessageDialog(null, "Gênero já adicionado!");
        }else{
            lista.addElement(select);
        }
    }//GEN-LAST:event_btnAdicionarGeneroActionPerformed

    private void btnCadastraAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraAnimeActionPerformed
        DefaultComboBoxModel lista = (DefaultComboBoxModel) boxEstudio.getModel();
        DefaultListModel listageneros = (DefaultListModel) listGeneros.getModel();
        
        if (txtNameAnime.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o nome do anime!");
        }else if(boxEstudio.getSelectedIndex() == 0 || boxEstudio.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um estudio!");
        }else if(listageneros.getSize() == 0){
            JOptionPane.showMessageDialog(null, "Adicione algum gênero!");
        }else if(bigtxtSinopse.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Adicione uma sinopse!");
        }else if(boxFaixa.getSelectedIndex() == 0 || boxFaixa.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Selecione uma faixa etaria!");
        }
        else{
            AnimeDAO dao = new AnimeDAO();
            Estudio estudio = (Estudio) lista.getSelectedItem();

            int tam = listageneros.getSize();
            ArrayList<Genero> generos = new ArrayList<>();

            for (int i = 0; i < tam; i++){
                generos.add((Genero) listageneros.get(i));
            }

            dao.cadastrarAnime(txtNameAnime.getText(), bigtxtSinopse.getText(), boxFaixa.getItemAt(boxFaixa.getSelectedIndex()), estudio.getIdestudio(), generos);
            ListarAnimes();
        }
        
    }//GEN-LAST:event_btnCadastraAnimeActionPerformed

    private void ConsultAnimeTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConsultAnimeTableFocusGained
        
    }//GEN-LAST:event_ConsultAnimeTableFocusGained

    private void ConsultAnimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultAnimeTableMouseClicked
        Anime anime = (Anime) ConsultAnimeTable.getValueAt(ConsultAnimeTable.getSelectedRow(), 1);
        
        bigtxtConsultAnimeSin.setText(anime.getSinopse());
        
    }//GEN-LAST:event_ConsultAnimeTableMouseClicked

    private void BuscarEstudios(){
        EstudioDAO dao = new EstudioDAO();
        List<Estudio> estudios = dao.listarEstudios();
        
        DefaultComboBoxModel lista = (DefaultComboBoxModel) boxEstudio.getModel();
        lista.addElement("");
        estudios.forEach((estudio) -> {
            lista.addElement(estudio);
        });
        
    }
    
    private void BuscarGeneros(){
        GeneroDAO dao = new GeneroDAO();
        List<Genero> generos = dao.listarGeneros();
        
        DefaultComboBoxModel lista = (DefaultComboBoxModel) boxGender.getModel();
        
        generos.forEach((genero) -> {
            lista.addElement(genero);
        });
        
    }
    
    private void ListarAnimes(){
        DefaultTableModel dados = (DefaultTableModel) ConsultAnimeTable.getModel();
        dados.setNumRows(0);
        
        AnimeDAO dao = new AnimeDAO();
        List<Anime> lista = dao.listarAnimes();
        
        for (Anime anime : lista){
            dados.addRow(new Object[]{
                anime.getIdanime(),
                anime,
                anime.getF_etaria(),
                anime.getMedia(),
                anime.Generos(),
                anime.getEstudio().getNome()
            });
        }
    }
    /*
    private void ListarAnimes(String s){
        DefaultTableModel dados = (DefaultTableModel) estudioTable.getModel();
        dados.setNumRows(0);
        
        EstudioDAO dao = new EstudioDAO();
        List<Estudio> lista = dao.BuscarEstudio(s);

        lista.forEach((estudio) -> {
            dados.addRow(new Object[]{
                estudio.getIdestudio(),
                estudio.getNome()
            });
        });
    }
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConsultAnimeSinLabel;
    private javax.swing.JTable ConsultAnimeTable;
    private javax.swing.JTextPane bigtxtConsultAnimeSin;
    private javax.swing.JTextPane bigtxtSinopse;
    private javax.swing.JComboBox<String> boxEstudio;
    private javax.swing.JComboBox<String> boxFaixa;
    private javax.swing.JComboBox<String> boxGender;
    private javax.swing.JButton btnAdicionarGenero;
    private javax.swing.JButton btnCadastraAnime;
    private javax.swing.JButton btnClearAnime;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JLabel consultAnimeLabel;
    private javax.swing.JLabel estudioLabel;
    private javax.swing.JLabel faixaLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<String> listGeneros;
    private javax.swing.JLabel nameAnimeLabel;
    private javax.swing.JLabel sinopseLabel;
    private javax.swing.JTextField txtConsultAnime;
    private javax.swing.JTextField txtNameAnime;
    // End of variables declaration//GEN-END:variables
}
