/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pctFormulario;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pctControle.Genero;
import pctDAO.GeneroDAO;

/**
 *
 * @author Luis Henrique
 */
public class GerenciaGenero extends javax.swing.JFrame {

    /**
     * Creates new form GerenciaEstudio
     */
    private String comp = "";
    
    public GerenciaGenero() {
        initComponents();
        ListarGeneros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastraGenero = new javax.swing.JButton();
        btnExcluirGenero = new javax.swing.JButton();
        btnToHomeEstudio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        generoTable = new javax.swing.JTable();
        digitaEstudioLabel = new javax.swing.JLabel();
        txtDigitaGenero = new javax.swing.JTextField();
        estudioLabel = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastraGenero.setText("Cadatrar Gênero");
        btnCadastraGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraGeneroActionPerformed(evt);
            }
        });

        btnExcluirGenero.setText("Excluir");
        btnExcluirGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirGeneroActionPerformed(evt);
            }
        });

        btnToHomeEstudio.setText("Voltar pra Home");

        generoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdGênero", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(generoTable);
        if (generoTable.getColumnModel().getColumnCount() > 0) {
            generoTable.getColumnModel().getColumn(0).setResizable(false);
            generoTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            generoTable.getColumnModel().getColumn(1).setResizable(false);
            generoTable.getColumnModel().getColumn(1).setPreferredWidth(550);
        }

        digitaEstudioLabel.setText("Digite o nome do Gênero:");

        txtDigitaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitaGeneroActionPerformed(evt);
            }
        });
        txtDigitaGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDigitaGeneroKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDigitaGeneroKeyReleased(evt);
            }
        });

        estudioLabel.setText("Gênero");

        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(digitaEstudioLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastraGenero))
                            .addComponent(estudioLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDigitaGenero)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnToHomeEstudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirGenero)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(digitaEstudioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDigitaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estudioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastraGenero))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToHomeEstudio)
                    .addComponent(btnExcluirGenero))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtDigitaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitaGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitaGeneroActionPerformed

    private void btnCadastraGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraGeneroActionPerformed
        
        if (txtGenero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio!");
            return;
        }
        try{
            GeneroDAO dao = new GeneroDAO();
            dao.cadastrarGenero(txtGenero.getText());
            LimparCampoCadastro();
            if (!txtDigitaGenero.getText().isEmpty()){
                ListarGeneros(txtDigitaGenero.getText());
            }else{
                ListarGeneros();
            }
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_btnCadastraGeneroActionPerformed

    private void txtDigitaGeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigitaGeneroKeyTyped
        
    }//GEN-LAST:event_txtDigitaGeneroKeyTyped

    private void txtDigitaGeneroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDigitaGeneroKeyReleased
        if (!txtDigitaGenero.getText().equals(this.comp)){
            ListarGeneros(txtDigitaGenero.getText());
        }else if(txtDigitaGenero.getText().isEmpty()){
            ListarGeneros();
        }
    }//GEN-LAST:event_txtDigitaGeneroKeyReleased

    private void btnExcluirGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirGeneroActionPerformed
        if (generoTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione Algum Estudio Para Excluir!");
        }else{
            Genero genero = new Genero(Integer.valueOf(generoTable.getValueAt(generoTable.getSelectedRow(), 0).toString()), generoTable.getValueAt(generoTable.getSelectedRow(), 1).toString());
            GeneroDAO dao = new GeneroDAO();
            
            dao.excluirGenero(genero);
            if (!txtDigitaGenero.getText().isEmpty()){
                ListarGeneros(txtDigitaGenero.getText());
            }else{
                ListarGeneros();
            }
        }
    }//GEN-LAST:event_btnExcluirGeneroActionPerformed

    private void LimparCampoCadastro(){
        txtGenero.setText("");
        
    }
    
    private void ListarGeneros(){
        
        DefaultTableModel dados = (DefaultTableModel) generoTable.getModel();
        dados.setNumRows(0);
        
        GeneroDAO dao = new GeneroDAO();
        List<Genero> lista = dao.listarGeneros();
        
        lista.forEach((genero) -> {
            dados.addRow(new Object[]{
                genero.getIdcategoria(),
                genero.getNome()
            });
        });
    }
    private void ListarGeneros(String s){
        DefaultTableModel dados = (DefaultTableModel) generoTable.getModel();
        dados.setNumRows(0);
        
        GeneroDAO dao = new GeneroDAO();
        List<Genero> lista = dao.BuscarGenero(s);

        lista.forEach((genero) -> {
            dados.addRow(new Object[]{
                genero.getIdcategoria(),
                genero.getNome()
            });
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaGenero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastraGenero;
    private javax.swing.JButton btnExcluirGenero;
    private javax.swing.JButton btnToHomeEstudio;
    private javax.swing.JLabel digitaEstudioLabel;
    private javax.swing.JLabel estudioLabel;
    private javax.swing.JTable generoTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDigitaGenero;
    private javax.swing.JTextField txtGenero;
    // End of variables declaration//GEN-END:variables
}
