/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pctFormulario;

import pctControle.Usuario;

/**
 *
 * @author Luis Henrique
 */
public class HomeAdm extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdm
     */
    private Usuario user;
    
    public HomeAdm(Usuario user) {
        this.user = user;
        initComponents();
        WelcomeADM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnGenGen = new javax.swing.JButton();
        btnGenAnime = new javax.swing.JButton();
        btnGenUsers = new javax.swing.JButton();
        btnGenEst = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        btnLogoutAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnGenGen.setText("Gerenciar Genêros");
        btnGenGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenGenActionPerformed(evt);
            }
        });

        btnGenAnime.setText("Gerenciar Animes");
        btnGenAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenAnimeActionPerformed(evt);
            }
        });

        btnGenUsers.setText("Gerenciar Usuário");
        btnGenUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenUsersActionPerformed(evt);
            }
        });

        btnGenEst.setText("Gerenciar Estúdios");
        btnGenEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenEstActionPerformed(evt);
            }
        });

        welcomeLabel.setText("Bem Vindo, ");

        btnLogoutAdm.setText("Logout");
        btnLogoutAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenGen, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenEst, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                                .addComponent(btnLogoutAdm))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(welcomeLabel)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addGap(55, 55, 55)
                .addComponent(btnGenUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenAnime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenGen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenEst)
                    .addComponent(btnLogoutAdm))
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutAdmActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutAdmActionPerformed

    private void btnGenUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenUsersActionPerformed
        new GerenciaUsuario(this.user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenUsersActionPerformed

    private void btnGenAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenAnimeActionPerformed
        new GerenciaAnime(this.user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenAnimeActionPerformed

    private void btnGenGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenGenActionPerformed
        new GerenciaGenero(this.user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenGenActionPerformed

    private void btnGenEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenEstActionPerformed
        new GerenciaEstudio(this.user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenEstActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void WelcomeADM(){
        try {
            welcomeLabel.setText("Bem Vindo, "+user.getUsername()+"!");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenAnime;
    private javax.swing.JButton btnGenEst;
    private javax.swing.JButton btnGenGen;
    private javax.swing.JButton btnGenUsers;
    private javax.swing.JButton btnLogoutAdm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
